# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=15, null=True)),
                ('item_type', models.CharField(blank=True, max_length=15, null=True)),
                ('item_subtype', models.CharField(blank=True, max_length=15, null=True)),
                ('rarity', models.CharField(blank=True, max_length=15, null=True)),
                ('carry_capacity', models.CharField(blank=True, max_length=15, null=True)),
                ('buy', models.CharField(blank=True, max_length=15, null=True)),
                ('sell', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
