# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_auto_20160718_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('defense', models.CharField(blank=True, max_length=255, null=True)),
                ('max_defense', models.CharField(blank=True, max_length=255, null=True)),
                ('fire_res', models.CharField(blank=True, max_length=255, null=True)),
                ('thunder_res', models.CharField(blank=True, max_length=255, null=True)),
                ('water_res', models.CharField(blank=True, max_length=255, null=True)),
                ('ice_res', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('hunter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('num_slots', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
