# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0006_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='dragon_res',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='rarity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
