# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0003_location_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('qtype', models.CharField(blank=True, max_length=255, null=True)),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('hub', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
                ('goal_type', models.CharField(blank=True, max_length=255, null=True)),
                ('hunter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.CharField(blank=True, max_length=255, null=True)),
                ('time_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.CharField(blank=True, max_length=255, null=True)),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                ('hrp', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_reward', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_hrp', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='Locations.Location')),
            ],
        ),
    ]
