# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0006_monster_ailments'),
        ('Quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterToQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('unstable', models.CharField(blank=True, max_length=255, null=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='Monsters.Monster')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='Quests.Quest')),
            ],
        ),
    ]
