# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0006_monster_ailments'),
        ('Quests', '0002_monstertoquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monstertoquest',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='monstertoquest',
            name='quest',
        ),
        migrations.AddField(
            model_name='quest',
            name='monsters',
            field=models.ManyToManyField(to='Monsters.Monster'),
        ),
        migrations.DeleteModel(
            name='MonsterToQuest',
        ),
    ]
