# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0003_auto_20160721_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='monsters',
            field=models.ManyToManyField(blank=True, null=True, to='Monsters.Monster'),
        ),
    ]
