# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0008_remove_monster_quests'),
        ('Quests', '0005_remove_quest_monsters'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='monsters',
            field=models.ManyToManyField(blank=True, null=True, to='Monsters.Monster'),
        ),
    ]
