# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('body_part', models.CharField(blank=True, max_length=255, null=True)),
                ('cut', models.CharField(blank=True, max_length=255, null=True)),
                ('impact', models.CharField(blank=True, max_length=255, null=True)),
                ('shot', models.CharField(blank=True, max_length=255, null=True)),
                ('fire', models.CharField(blank=True, max_length=255, null=True)),
                ('water', models.CharField(blank=True, max_length=255, null=True)),
                ('ice', models.CharField(blank=True, max_length=255, null=True)),
                ('thunder', models.CharField(blank=True, max_length=255, null=True)),
                ('dragon', models.CharField(blank=True, max_length=255, null=True)),
                ('ko', models.CharField(blank=True, max_length=255, null=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='Monsters.Monster')),
            ],
        ),
    ]
