# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_location_key'),
        ('Monsters', '0002_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_area', models.CharField(blank=True, max_length=255, null=True)),
                ('move_area', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_area', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='Locations.Location')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitat', to='Monsters.Monster')),
            ],
        ),
    ]
