# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0004_auto_20160720_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('fire', models.CharField(blank=True, max_length=255, null=True)),
                ('water', models.CharField(blank=True, max_length=255, null=True)),
                ('thunder', models.CharField(blank=True, max_length=255, null=True)),
                ('ice', models.CharField(blank=True, max_length=255, null=True)),
                ('dragon', models.CharField(blank=True, max_length=255, null=True)),
                ('poison', models.CharField(blank=True, max_length=255, null=True)),
                ('para', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep', models.CharField(blank=True, max_length=255, null=True)),
                ('pitfall_trap', models.CharField(blank=True, max_length=255, null=True)),
                ('shock_trap', models.CharField(blank=True, max_length=255, null=True)),
                ('flash_bomb', models.CharField(blank=True, max_length=255, null=True)),
                ('sonic_bomb', models.CharField(blank=True, max_length=255, null=True)),
                ('dung_bomb', models.CharField(blank=True, max_length=255, null=True)),
                ('meat', models.CharField(blank=True, max_length=255, null=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakness', to='Monsters.Monster')),
            ],
        ),
    ]
