# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0004_auto_20160721_2124'),
        ('Monsters', '0006_monster_ailments'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='quests',
            field=models.ManyToManyField(blank=True, null=True, to='Quests.Quest'),
        ),
    ]
