# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_img',
            field=models.ImageField(default='01.png', upload_to='Images/Locations'),
        ),
    ]
